Improve @std/esm compatibility
Using esm triggered errors:

    require = require('@std/esm')(module, { cjs: true, esm: 'js' });
    var JSZip = require("jszip");
    var zip = new JSZip();
    zip.file("test", "test")
    // TypeError: arguments[i].hasOwnProperty is not a function

Pako was just updated to fix this one too, we also include the fix.